---
title: "Descriptives of Cancelled Appointments Table"
output: html_notebook
---

```{r}

library(here)
library(tidyverse)
library(kableExtra)

data <- read_rds(here("Generated data","data_with_correct_summary_cancellation_variables.rds"))

```

# Countsof Any Self-cancellations

```{r}


data %>%
  select(record_id, starts_with("Any_Self_Cancelled")) %>%
  pivot_longer(cols = Any_Self_Cancelled_Appt_T1:Any_Self_Cancelled_Appt_T3,
               names_to = c('Type','Timepoint'),
               names_pattern = "(.*)_T(.)",
               values_transform = list(value = as.character)
              ) %>%
  count(Timepoint,value) %>%
  group_by(Timepoint) %>%
  summarize(value = value,
            n = n,
    percentage = n / sum(n)) %>%
  mutate(`Percentage to Report` = round(percentage * 100,2)) %>%
  filter(value == TRUE)


```


# Counts of Screening Cancellations Among Those With Self-Cancellations

```{r}


data %>%
  select(record_id, starts_with("Any_Self_Cancelled"), starts_with("Any_Cancer_Screening_Cancellations")) %>%
  pivot_longer(cols = Any_Self_Cancelled_Appt_T1:Any_Cancer_Screening_Cancellations_T3,
               names_to = c('Type','Timepoint'),
               names_pattern = "(.*)_T(.)",
               values_transform = list(value = as.character)
              ) %>%
    pivot_wider(names_from = Type) %>%
  mutate(across(everything(), as.factor)) %>%
  count(Timepoint, Any_Self_Cancelled_Appt, Any_Cancer_Screening_Cancellations) %>%
  group_by(Timepoint, Any_Self_Cancelled_Appt) %>%
   summarize(Any_Cancer_Screening_Cancellations = Any_Cancer_Screening_Cancellations,
            n = n,
    percentage = n / sum(n)) %>%
  mutate(`Percentage to Report` = round(percentage * 100,2)) %>%
  filter(Any_Self_Cancelled_Appt == TRUE) %>%
  filter(Any_Cancer_Screening_Cancellations == "Yes:Me")

```
# Counts of any provider cancellations

```{r}


data %>%
  select(record_id, starts_with("Any_Provider_Cancelled")) %>%
  pivot_longer(cols = Any_Provider_Cancelled_Appt_T1:Any_Provider_Cancelled_Appt_T3,
               names_to = c('Type','Timepoint'),
               names_pattern = "(.*)_T(.)",
               values_transform = list(value = as.character)
              ) %>%
  count(Timepoint,value) %>%
  group_by(Timepoint) %>%
  summarize(value = value,
            n = n,
    percentage = n / sum(n)) %>%
  mutate(`Percentage to Report` = round(percentage * 100,2)) %>%
  filter(value == TRUE)


```


# Counts of Screening Cancellations Among Those With Self-Cancellations

```{r}


data %>%
  select(record_id, starts_with("Any_Provider_Cancelled"), starts_with("Any_Cancer_Screening_Cancellations")) %>%
  pivot_longer(cols = Any_Provider_Cancelled_Appt_T1:Any_Cancer_Screening_Cancellations_T3,
               names_to = c('Type','Timepoint'),
               names_pattern = "(.*)_T(.)",
               values_transform = list(value = as.character)
              ) %>%
    pivot_wider(names_from = Type) %>%
  mutate(across(everything(), as.factor)) %>%
  count(Timepoint, Any_Provider_Cancelled_Appt, Any_Cancer_Screening_Cancellations) %>%
  group_by(Timepoint, Any_Provider_Cancelled_Appt) %>%
   summarize(Any_Cancer_Screening_Cancellations = Any_Cancer_Screening_Cancellations,
            n = n,
    percentage = n / sum(n)) %>%
  mutate(`Percentage to Report` = round(percentage * 100,2)) %>%
  filter(Any_Provider_Cancelled_Appt == TRUE) %>%
  filter(Any_Cancer_Screening_Cancellations == "Yes:My healthcare provider")

```