---
title: "Combine Variables for Missed Appointments"
output: html_notebook
---


```{r}
library(tidyverse)
library(here)


```


```{r}

data_all <- read_csv(file = '~/Research - Lives on HD/Covid Canceled Medical Appointments Analysis/Raw Data/COVID Main Database All_06-17-21.csv')
  
data <- 
  data_all %>%
  select(record_id, adh_cancer_apt_T1, adh_cancer_apt_T2, adh_cancer_apt_T3,
         adh_cancer_you_T1, adh_cancer_you_T2, adh_cancer_you_T3,
         adh_cancer_test_T1, adh_cancer_test_T2, adh_cancer_test_T3,
         adh_cancer_test_who_T1, adh_cancer_test_who_T2, adh_cancer_test_who_T3) %>%
  
  mutate(adh_cancer_apt_T1 = factor(adh_cancer_apt_T1,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
         adh_cancer_apt_T2 = factor(adh_cancer_apt_T2,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
         adh_cancer_apt_T3 = factor(adh_cancer_apt_T3,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
         # this variable has flipped labels for levels 2 and 3 compared to prior variables
         adh_cancer_test_T1 = factor(adh_cancer_test_T1,
                                     levels = c(0,1,2,3),
                                       labels = c('No','Yes', 'Not sure', 'I did not have anything scheduled')),
                  adh_cancer_test_T2 = factor(adh_cancer_test_T2,
                                     levels = c(0,1,2,3),
                                       labels = c('No','Yes', 'Not sure', 'I did not have anything scheduled')),
                  adh_cancer_test_T3 = factor(adh_cancer_test_T3,
                                     levels = c(0,1,2,3),
                                    labels = c('No','Yes', 'Not sure', 'I did not have anything scheduled')),
         adh_cancer_you_T1 = factor(adh_cancer_you_T1,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
         adh_cancer_you_T2 = factor(adh_cancer_you_T2,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
         adh_cancer_you_T3 = factor(adh_cancer_you_T3,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
    adh_cancer_test_who_T1 = fct_explicit_na(factor(adh_cancer_test_who_T1,
                                         levels = c(1,2),
                                         labels = c('Me','My healthcare provider'))),
         adh_cancer_test_who_T2 = fct_explicit_na(factor(adh_cancer_test_who_T2,
                                         levels = c(1,2),
                                         labels = c('Me','My healthcare provider'))),
         adh_cancer_test_who_T3 = fct_explicit_na(factor(adh_cancer_test_who_T3,
                                         levels = c(1,2),
                                         labels = c('Me','My healthcare provider'))))
  

table(data$adh_cancer_test_who_T1)
table(data$adh_cancer_test_who_T2)
table(data$adh_cancer_test_who_T3)


View(tibble(data$adh_cancer_test_T3, data$adh_cancer_test_who_T3))
```


```{r}

data <-
  data %>%
  mutate(Any_Self_Cancelled_Appt_T1 = (adh_cancer_you_T1 == "Yes" | adh_cancer_test_who_T1 == "Me"),
         Any_Self_Cancelled_Appt_T2 = (adh_cancer_you_T2 == "Yes" | adh_cancer_test_who_T2 == "Me"),
         Any_Self_Cancelled_Appt_T3 = (adh_cancer_you_T3 == "Yes" | adh_cancer_test_who_T3 == "Me"),
         Any_Provider_Cancelled_Appt_T1 = (adh_cancer_apt_T1 == "Yes" | adh_cancer_test_who_T1 == "My provider"),
         Any_Provider_Cancelled_Appt_T2 = (adh_cancer_apt_T2 == "Yes" | adh_cancer_test_who_T2 == "My provider"),
         Any_Provider_Cancelled_Appt_T3 = (adh_cancer_apt_T3 == "Yes" | adh_cancer_test_who_T3 == "My provider"))

table(data$Any_Provider_Cancelled_Appt_T3)

View(data)

```
