---
title: "R Notebook"
output: html_notebook
---

# Read in libraries and data

```{r}

library(tidyverse)
library(here)
library(pander)

data <- read_csv(here('Generated Data','Analytic dataset.csv'))

```

# Examine frequencies


```{r}

data %>%
  
  # Lauren - check out pivot_longer() and pivot_wider() tutorials to get a sense of what this does. This command is one of the most powerful ones in R imo :). Basically what it does is reformat the data so that I can just then group and count trues/falses once rather than separately for each variable in the next lines.
  pivot_longer(cols = Any_Self_Cancelled_Appt_T1:Any_Provider_Cancelled_Appt_T3, 
               names_to = c('Type','Timepoint'),
               names_pattern = '(.*)_T(.*)') %>%
  
  
  # group so that we get trues/falses by type of code, by timepoint
  group_by(Type, Timepoint) %>%
  
  # compute number of trues/falses
  summarise(trues = sum(value == 'TRUE', na.rm = TRUE),
            falses = sum(value == 'FALSE', na.rm = TRUE)) %>%
  
  # display in ASCII (easy to read in RStudio)
  pander()
  

```

# For convenience, here is the output printed


----------------------------------------------------------
            Type               Timepoint   trues   falses 
----------------------------- ----------- ------- --------
 Any_Provider_Cancelled_Appt       1        65       81   

 Any_Provider_Cancelled_Appt       2        47       93   

 Any_Provider_Cancelled_Appt       3        11      109   

   Any_Self_Cancelled_Appt         1        49       97   

   Any_Self_Cancelled_Appt         2        45       95   

   Any_Self_Cancelled_Appt         3        27       93   
----------------------------------------------------------

