---
title: "Examine rates of missing appointments"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

# Read in

```{r}
library(tidyverse)
library(here)
library(pander)

data <- read_rds(file = here("Generated data","data_with_correct_summary_cancellation_variables.rds"))

```

# Examine specific variables

## For revise and resubmit, any cancelled appointments (incl screenings) or screenings specifically

### Any Cancelled Appt T1
```{r}

table(data$Any_Cancelled_Appt_T1)

89/(57+89)

```

### Any Cancelled Appt  T2
```{r}

table(data$Any_Cancelled_Appt_T2)

75/(65+75)

```

### T3
```{r}

table(data$Any_Cancelled_Appt_T3)

35/(85+35)

```


### Any Cancelled Screening T1
```{r}

table(data$Any_Cancelled_Screening_T1)

31/(114+31)

```

### Any Cancelled Screening  T2
```{r}

table(data$Any_Cancelled_Screening_T2)

18/(122+18)

```

### T3
```{r}

table(data$Any_Cancelled_Screening_T3)

5/(114+5)

```


## Self-cancelled cancer screenings out of total

### T1
```{r}

table(data$Any_Self_Cancelled_Screening_T1)

15/(130+15)

```

### T2
```{r}

table(data$Any_Self_Cancelled_Screening_T2)

7/(133+7)

```

### T3
```{r}

table(data$Any_Self_Cancelled_Screening_T3)

3/(116+3)

```

## Provider-cancelled cancer screenings out of total

### T1
```{r}

table(data$Any_Provider_Cancelled_Screening_T1)

16/(129+16)

```

### T2
```{r}

table(data$Any_Provider_Cancelled_Screening_T2)

11/(129+11)

```

### T3
```{r}

table(data$Any_Provider_Cancelled_Screening_T3)

2/(117+2)

```


