---
title: "Mediation Models"
output: html_document
---

#Read in libraries and data

```{r}
library(here)
library(tidyverse)
library(lavaan) 


setwd("/Users/laurenfinkelstein/Desktop/Arch Lab/COVID Appt Paper/Data")
data <-read.csv("CURRENT Full Covid Data.csv", header=T)

```

#Check data
```{r}

summary(data$cfi_mean_T1)
is.numeric(data$cfi_mean_T1)

summary(data$gad7_tot_T1)
is.numeric(data$gad7_tot_T1)

summary(data$phq8_tot_T1)
is.numeric(data$phq8_tot_T1)

summary(data$copefull_ACS_mean_T1 )
is.numeric(data$copefull_ACS_mean_T1)

summary(data$copefull_AvCS_mean_T1)
is.numeric(data$copefull_AvCS_mean_T1)

summary(data$Any_Self_Cancelled_Appt_T1)

```

#Create true/false variable for any patient-cancelled cancer screening and would delay in seeking medical care for a suspicious symptom 
```{r}
data <- 
  data %>%
  
  mutate(adh_cancer_test_T1 = factor(adh_cancer_test_T1,
                                     levels = c(0,1,2,3),
                                       labels = c('No','Yes', 'Not sure', 'I did not have anything scheduled')),
                  adh_cancer_test_T2 = factor(adh_cancer_test_T2,
                                     levels = c(0,1,2,3),
                                       labels = c('No','Yes', 'Not sure', 'I did not have anything scheduled')),
                  adh_cancer_test_T3 = factor(adh_cancer_test_T3,
                                     levels = c(0,1,2,3),
                                    labels = c('No','Yes', 'Not sure', 'I did not have anything scheduled')),
         adh_cancer_you_T1 = factor(adh_cancer_you_T1,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
         adh_cancer_you_T2 = factor(adh_cancer_you_T2,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
         adh_cancer_you_T3 = factor(adh_cancer_you_T3,
                                         levels = c(0,1,2,3),
                                         labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
        adh_cancer_test_who_T1 = fct_explicit_na(factor(adh_cancer_test_who_T1,
                                         levels = c(1,2),
                                         labels = c('Me','My healthcare provider'))),
         adh_cancer_test_who_T2 = fct_explicit_na(factor(adh_cancer_test_who_T2,
                                         levels = c(1,2),
                                         labels = c('Me','My healthcare provider'))),
         adh_cancer_test_who_T3 = fct_explicit_na(factor(adh_cancer_test_who_T3,
                                         levels = c(1,2),
                                         labels = c('Me','My healthcare provider'))),
        adh_cancer_sx_T1 = factor(adh_cancer_sx_T1,
                                         levels = c(1,2,3,4,5),
                                         labels = c('Extremely unlikely','Unlikely','Neutral','Likely','Extremely Likely')),
        adh_cancer_sx_T2 = factor(adh_cancer_sx_T2,
                                         levels = c(1,2,3,4,5),
                                         labels = c('Extremely unlikely','Unlikely','Neutral','Likely','Extremely Likely')),
        adh_cancer_sx_T3 = factor(adh_cancer_sx_T3,
                                         levels = c(1,2,3,4,5),
                                         labels = c('Extremely unlikely','Unlikely','Neutral','Likely','Extremely Likely')))
                                         

data <-
  data %>%
  mutate(Self_Cancelled_Screening_T1 = (adh_cancer_test_who_T1 == "Me"),
         Self_Cancelled_Screening_T2 = (adh_cancer_test_who_T2 == "Me"),
         Self_Cancelled_Screening_T3 = (adh_cancer_test_who_T3 == "Me"),
         #Per 8/6/21 group discussion, extremely unlikely + unlikely = no delay (false) and neutral + Likely + extremely likely = yes delay (true)
         Delay_Suspicious_T1 = (adh_cancer_sx_T1 == "Neutral" | adh_cancer_sx_T1 == "Likely" | adh_cancer_sx_T1 == "Extremely Likely"),
         Delay_Suspicious_T2 = (adh_cancer_sx_T2 == "Neutral" | adh_cancer_sx_T2 == "Likely" | adh_cancer_sx_T2 == "Extremely Likely"),
         Delay_Suspicious_T3 = (adh_cancer_sx_T3 == "Neutral" | adh_cancer_sx_T3 == "Likely" | adh_cancer_sx_T3 == "Extremely Likely"))

table(data$Self_Cancelled_Screening_T1)
table(data$Self_Cancelled_Screening_T2)
table(data$Self_Cancelled_Screening_T3)

table(data$Delay_Suspicious_T1)
table(data$Delay_Suspicious_T2)
table(data$Delay_Suspicious_T3)
```


#Generic mediation model
```{r}

contemporaneousMediationFit <- function(predictor_var, mediator_var, outcome_var) {

mediation.model.generic <- '

# a path
Mediator ~ a_path*Predictor

# b path
Outcome ~ b_path*Mediator

# c prime path
Outcome ~ cprime_path*Predictor



# tells lavaan to estimate the product of ab and its p value
ab := a_path*b_path

'
mediation.model <-  str_replace_all(mediation.model.generic,
                                     c("Outcome" = outcome_var,
                                       "Mediator" = mediator_var,
                                       "Predictor" = predictor_var))


# model is estimated
mediation.fit <- lavaan::sem(model = mediation.model,
            data = data,
            bootstrap = 1000,
            missing = 'listwise',
            link = 'probit',
            se = 'bootstrap',
            estimator = 'WLS',
            ordered = c('Any_Self_Cancelled_Appt_T1', 'Self_Cancelled_Screening_T1','Delay_Suspicious_T1','Any_Self_Cancelled_Appt_T2', 'Self_Cancelled_Screening_T2','Delay_Suspicious_T2','Any_Self_Cancelled_Appt_T3', 'Self_Cancelled_Screening_T3','Delay_Suspicious_T3'))

return(mediation.fit)
}

```

#Time 1 Models
```{r}
#Time 1: Predictor = general COVID-19 fears, Outcome = any patient-cancelled appointment

#Mediator = anxiety
set.seed(1)
General_Anx_Any <- contemporaneousMediationFit('cfi_mean_T1','gad7_tot_T1','Any_Self_Cancelled_Appt_T1')
summary(General_Anx_Any)

#Mediator = depression
set.seed(1)
General_Dep_Any <- contemporaneousMediationFit('cfi_mean_T1','phq8_tot_T1','Any_Self_Cancelled_Appt_T1')
summary(General_Dep_Any)

#Mediator = approach coping
set.seed(1)
General_Approach_Any <- contemporaneousMediationFit('cfi_mean_T1','copefull_ACS_mean_T1 ','Any_Self_Cancelled_Appt_T1')
summary(General_Approach_Any)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Any <- contemporaneousMediationFit('cfi_mean_T1','copefull_AvCS_mean_T1','Any_Self_Cancelled_Appt_T1')
summary(General_Avoid_Any)



#_____________________________________________________________________________________________________________________________


#Time 1: Predictor = cancer-related COVID-19 fears, Outcome = any patient-cancelled appointment

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Any <- contemporaneousMediationFit('cfi_survivor_mean_T1','gad7_tot_T1','Any_Self_Cancelled_Appt_T1')
summary(Cancer_Anx_Any)

#Mediator = depression
set.seed(1)
Cancer_Dep_Any <- contemporaneousMediationFit('cfi_survivor_mean_T1','phq8_tot_T1','Any_Self_Cancelled_Appt_T1')
summary(Cancer_Dep_Any)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Any <- contemporaneousMediationFit('cfi_survivor_mean_T1','copefull_ACS_mean_T1 ','Any_Self_Cancelled_Appt_T1')
summary(Cancer_Approach_Any)

#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Any <- contemporaneousMediationFit('cfi_survivor_mean_T1','copefull_AvCS_mean_T1','Any_Self_Cancelled_Appt_T1')
summary(Cancer_Avoid_Any)



#_____________________________________________________________________________________________________________________________

#Time 1: Predictor = general COVID-19 fears, Outcome = patient-cancelled cancer screening


#Mediator = anxiety
set.seed(1)
General_Anx_Screen <- contemporaneousMediationFit('cfi_mean_T1','gad7_tot_T1','Self_Cancelled_Screening_T1')
summary(General_Anx_Screen)

#Mediator = depression
set.seed(1)
General_Dep_Screen <- contemporaneousMediationFit('cfi_mean_T1','phq8_tot_T1','Self_Cancelled_Screening_T1')
summary(General_Dep_Screen)

#Mediator = approach coping
set.seed(1)
General_Approach_Screen <- contemporaneousMediationFit('cfi_mean_T1','copefull_ACS_mean_T1 ','Self_Cancelled_Screening_T1')
summary(General_Approach_Screen)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Screen <- contemporaneousMediationFit('cfi_mean_T1','copefull_AvCS_mean_T1','Self_Cancelled_Screening_T1')
summary(General_Avoid_Screen)



#_____________________________________________________________________________________________________________________________

#Time 1: Predictor = cancer-related COVID-19 fears, Outcome = patient-cancelled cancer screening

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Screen <- contemporaneousMediationFit('cfi_survivor_mean_T1','gad7_tot_T1','Self_Cancelled_Screening_T1')
summary(Cancer_Anx_Screen)

#Mediator = depression
set.seed(1)
Cancer_Dep_Screen <- contemporaneousMediationFit('cfi_survivor_mean_T1','phq8_tot_T1','Self_Cancelled_Screening_T1')
summary(Cancer_Dep_Screen)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Screen <- contemporaneousMediationFit('cfi_survivor_mean_T1','copefull_ACS_mean_T1 ','Self_Cancelled_Screening_T1')
summary(Cancer_Approach_Screen)

#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Screen <- contemporaneousMediationFit('cfi_survivor_mean_T1','copefull_AvCS_mean_T1','Self_Cancelled_Screening_T1')
summary(Cancer_Avoid_Screen)



#_____________________________________________________________________________________________________________________________

#Time 1: Predictor = general COVID-19 fears, Outcome = delaying appointment for suspicious symptom

#Mediator = anxiety
set.seed(1)
General_Anx_Delay <- contemporaneousMediationFit('cfi_mean_T1','gad7_tot_T1','Delay_Suspicious_T1')
summary(General_Anx_Delay)

#Mediator = depression
set.seed(1)
General_Dep_Delay <- contemporaneousMediationFit('cfi_mean_T1','phq8_tot_T1','Delay_Suspicious_T1')
summary(General_Dep_Delay)

#Mediator = approach coping
set.seed(1)
General_Approach_Delay <- contemporaneousMediationFit('cfi_mean_T1','copefull_ACS_mean_T1 ','Delay_Suspicious_T1')
summary(General_Approach_Delay)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Delay <- contemporaneousMediationFit('cfi_mean_T1','copefull_AvCS_mean_T1','Delay_Suspicious_T1')
summary(General_Avoid_Delay)



#_____________________________________________________________________________________________________________________________

#Time 1: Predictor = cancer-related COVID-19 fears, Outcome = delaying appointment for suspicious symptom

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Delay <- contemporaneousMediationFit('cfi_survivor_mean_T1','gad7_tot_T1','Delay_Suspicious_T1')
summary(Cancer_Anx_Delay)

#Mediator = depression
set.seed(1)
Cancer_Dep_Delay <- contemporaneousMediationFit('cfi_survivor_mean_T1','phq8_tot_T1','Delay_Suspicious_T1')
summary(Cancer_Dep_Delay)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Delay <- contemporaneousMediationFit('cfi_survivor_mean_T1','copefull_ACS_mean_T1 ','Delay_Suspicious_T1')
summary(Cancer_Approach_Delay)

#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Delay <- contemporaneousMediationFit('cfi_survivor_mean_T1','copefull_AvCS_mean_T1','Delay_Suspicious_T1')
summary(Cancer_Avoid_Delay)

```



#Time 2 Models
```{r}
#Time 2: Predictor = general COVID-19 fears, Outcome = any patient-cancelled appointment

#Mediator = anxiety
set.seed(1)
General_Anx_Any2 <- contemporaneousMediationFit('cfi_mean_T2','gad7_tot_T2','Any_Self_Cancelled_Appt_T2')
summary(General_Anx_Any2)

#Mediator = depression
set.seed(1)
General_Dep_Any2 <- contemporaneousMediationFit('cfi_mean_T2','phq8_tot_T2','Any_Self_Cancelled_Appt_T2')
summary(General_Dep_Any2)

#Mediator = approach coping
set.seed(1)
General_Approach_Any2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_ACS_mean_T2','Any_Self_Cancelled_Appt_T2')
summary(General_Approach_Any2)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Any2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_AvCS_mean_T2','Any_Self_Cancelled_Appt_T2')
summary(General_Avoid_Any2)



#_____________________________________________________________________________________________________________________________


#Time 2: Predictor = cancer-related COVID-19 fears, Outcome = any patient-cancelled appointment

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Any2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','gad7_tot_T2','Any_Self_Cancelled_Appt_T2')
summary(Cancer_Anx_Any2)

#Mediator = depression
set.seed(1)
Cancer_Dep_Any2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','phq8_tot_T2','Any_Self_Cancelled_Appt_T2')
summary(Cancer_Dep_Any2)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Any2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_ACS_mean_T2','Any_Self_Cancelled_Appt_T2')
summary(Cancer_Approach_Any2)

#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Any2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_AvCS_mean_T2','Any_Self_Cancelled_Appt_T2')
summary(Cancer_Avoid_Any2)



#_____________________________________________________________________________________________________________________________

#Time 2: Predictor = general COVID-19 fears, Outcome = patient-cancelled cancer screening


#Mediator = anxiety
set.seed(1)
General_Anx_Screen2 <- contemporaneousMediationFit('cfi_mean_T2','gad7_tot_T2','Self_Cancelled_Screening_T2')
summary(General_Anx_Screen2)

#Mediator = depression
set.seed(1)
General_Dep_Screen2 <- contemporaneousMediationFit('cfi_mean_T2','phq8_tot_T2','Self_Cancelled_Screening_T2')
summary(General_Dep_Screen2)

#Mediator = approach coping
set.seed(1)
General_Approach_Screen2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_ACS_mean_T2','Self_Cancelled_Screening_T2')
summary(General_Approach_Screen2)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Screen2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_AvCS_mean_T2','Self_Cancelled_Screening_T2')
summary(General_Avoid_Screen2)



#_____________________________________________________________________________________________________________________________

#Time 2: Predictor = cancer-related COVID-19 fears, Outcome = patient-cancelled cancer screening

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Screen2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','gad7_tot_T2','Self_Cancelled_Screening_T2')
summary(Cancer_Anx_Screen2)

#Mediator = depression
set.seed(1)
Cancer_Dep_Screen2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','phq8_tot_T2','Self_Cancelled_Screening_T2')
summary(Cancer_Dep_Screen2)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Screen2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_ACS_mean_T2 ','Self_Cancelled_Screening_T2')
summary(Cancer_Approach_Screen2)


#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Screen2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_AvCS_mean_T2','Self_Cancelled_Screening_T2')
summary(Cancer_Avoid_Screen2)



#_____________________________________________________________________________________________________________________________

#Time 2: Predictor = general COVID-19 fears, Outcome = delaying appointment for suspicious symptom

#Mediator = anxiety
set.seed(1)
General_Anx_Delay2 <- contemporaneousMediationFit('cfi_mean_T2','gad7_tot_T2','Delay_Suspicious_T2')
summary(General_Anx_Delay2)

#Mediator = depression
set.seed(1)
General_Dep_Delay2 <- contemporaneousMediationFit('cfi_mean_T2','phq8_tot_T2','Delay_Suspicious_T2')
summary(General_Dep_Delay2)

#Mediator = approach coping
set.seed(1)
General_Approach_Delay2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_ACS_mean_T2','Delay_Suspicious_T2')
summary(General_Approach_Delay2)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Delay2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_AvCS_mean_T2','Delay_Suspicious_T2')
summary(General_Avoid_Delay2)


#_____________________________________________________________________________________________________________________________

#Time 2: Predictor = cancer-related COVID-19 fears, Outcome = delaying appointment for suspicious symptom

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Delay2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','gad7_tot_T2','Delay_Suspicious_T2')
summary(Cancer_Anx_Delay2)

#Mediator = depression
set.seed(1)
Cancer_Dep_Delay2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','phq8_tot_T2','Delay_Suspicious_T2')
summary(Cancer_Dep_Delay2)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Delay2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_ACS_mean_T2','Delay_Suspicious_T2')
summary(Cancer_Approach_Delay2)

#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Delay2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_AvCS_mean_T2','Delay_Suspicious_T2')
summary(Cancer_Avoid_Delay2)
```
#Time 3 Models--INCOMPLETE, DOING CORRELATIONS FOR NOW

```{r}
#Time 3: Predictor = general COVID-19 fears, Outcome = any patient-cancelled appointment

#Mediator = anxiety
set.seed(1)
General_Anx_Any3 <- contemporaneousMediationFit('cfi_mean_T3','gad7_tot_T3','Any_Self_Cancelled_Appt_T3')
summary(General_Anx_Any3)

#Mediator = depression
set.seed(1)
General_Dep_Any3 <- contemporaneousMediationFit('cfi_mean_T3','phq8_tot_T3','Any_Self_Cancelled_Appt_T3')
summary(General_Dep_Any3)

#Mediator = approach coping
set.seed(1)
General_Approach_Any3 <- contemporaneousMediationFit('cfi_mean_T3','copefull_ACS_mean_T3','Any_Self_Cancelled_Appt_T3')
summary(General_Approach_Any3)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Any3 <- contemporaneousMediationFit('cfi_mean_T3','copefull_AvCS_mean_T3','Any_Self_Cancelled_Appt_T3')
summary(General_Avoid_Any3)



#_____________________________________________________________________________________________________________________________


#Time 2: Predictor = cancer-related COVID-19 fears, Outcome = any patient-cancelled appointment

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Any2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','gad7_tot_T2','Any_Self_Cancelled_Appt_T2')
summary(Cancer_Anx_Any2)

#Mediator = depression
set.seed(1)
Cancer_Dep_Any2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','phq8_tot_T2','Any_Self_Cancelled_Appt_T2')
summary(Cancer_Dep_Any2)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Any2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_ACS_mean_T2','Any_Self_Cancelled_Appt_T2')
summary(Cancer_Approach_Any2)

#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Any2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_AvCS_mean_T2','Any_Self_Cancelled_Appt_T2')
summary(Cancer_Avoid_Any2)



#_____________________________________________________________________________________________________________________________

#Time 2: Predictor = general COVID-19 fears, Outcome = patient-cancelled cancer screening


#Mediator = anxiety
set.seed(1)
General_Anx_Screen2 <- contemporaneousMediationFit('cfi_mean_T2','gad7_tot_T2','Self_Cancelled_Screening_T2')
summary(General_Anx_Screen2)

#Mediator = depression
set.seed(1)
General_Dep_Screen2 <- contemporaneousMediationFit('cfi_mean_T2','phq8_tot_T2','Self_Cancelled_Screening_T2')
summary(General_Dep_Screen2)

#Mediator = approach coping
set.seed(1)
General_Approach_Screen2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_ACS_mean_T2','Self_Cancelled_Screening_T2')
summary(General_Approach_Screen2)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Screen2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_AvCS_mean_T2','Self_Cancelled_Screening_T2')
summary(General_Avoid_Screen2)



#_____________________________________________________________________________________________________________________________

#Time 2: Predictor = cancer-related COVID-19 fears, Outcome = patient-cancelled cancer screening

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Screen2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','gad7_tot_T2','Self_Cancelled_Screening_T2')
summary(Cancer_Anx_Screen2)

#Mediator = depression
set.seed(1)
Cancer_Dep_Screen2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','phq8_tot_T2','Self_Cancelled_Screening_T2')
summary(Cancer_Dep_Screen2)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Screen2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_ACS_mean_T2 ','Self_Cancelled_Screening_T2')
summary(Cancer_Approach_Screen2)


#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Screen2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_AvCS_mean_T2','Self_Cancelled_Screening_T2')
summary(Cancer_Avoid_Screen2)



#_____________________________________________________________________________________________________________________________

#Time 2: Predictor = general COVID-19 fears, Outcome = delaying appointment for suspicious symptom

#Mediator = anxiety
set.seed(1)
General_Anx_Delay2 <- contemporaneousMediationFit('cfi_mean_T2','gad7_tot_T2','Delay_Suspicious_T2')
summary(General_Anx_Delay2)

#Mediator = depression
set.seed(1)
General_Dep_Delay2 <- contemporaneousMediationFit('cfi_mean_T2','phq8_tot_T2','Delay_Suspicious_T2')
summary(General_Dep_Delay2)

#Mediator = approach coping
set.seed(1)
General_Approach_Delay2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_ACS_mean_T2','Delay_Suspicious_T2')
summary(General_Approach_Delay2)

#Mediator = avoidance coping
set.seed(1)
General_Avoid_Delay2 <- contemporaneousMediationFit('cfi_mean_T2','copefull_AvCS_mean_T2','Delay_Suspicious_T2')
summary(General_Avoid_Delay2)


#_____________________________________________________________________________________________________________________________

#Time 2: Predictor = cancer-related COVID-19 fears, Outcome = delaying appointment for suspicious symptom

#Mediator = anxiety
set.seed(1)
Cancer_Anx_Delay2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','gad7_tot_T2','Delay_Suspicious_T2')
summary(Cancer_Anx_Delay2)

#Mediator = depression
set.seed(1)
Cancer_Dep_Delay2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','phq8_tot_T2','Delay_Suspicious_T2')
summary(Cancer_Dep_Delay2)

#Mediator = approach coping
set.seed(1)
Cancer_Approach_Delay2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_ACS_mean_T2','Delay_Suspicious_T2')
summary(Cancer_Approach_Delay2)

#Mediator = avoidance coping
set.seed(1)
Cancer_Avoid_Delay2 <- contemporaneousMediationFit('cfi_survivor_mean_T2','copefull_AvCS_mean_T2','Delay_Suspicious_T2')
summary(Cancer_Avoid_Delay2)
```


#C paths
```{r}

contemporaneousUnmediatedFit <- function(predictor_var, outcome_var) {
  
  cpath.model.generic <- '
# c prime path
Outcome ~ c_path*Predictor
'
  cpath.model <-  str_replace_all(cpath.model.generic,
                                  c("Outcome" = outcome_var,
                                    "Predictor" = predictor_var))
  
  # model is estimated
  cpath.model.fit <- lavaan::sem(model = cpath.model,
            data = data,
            bootstrap = 1000,
            missing = 'listwise',
            link = 'probit',
            se = 'bootstrap',
            estimator = 'WLS',
            ordered = c('Any_Self_Cancelled_Appt_T1','Self_Cancelled_Screening_T1','Delay_Suspicious_T1','Any_Self_Cancelled_Appt_T2','Self_Cancelled_Screening_T2','Delay_Suspicious_T2','Any_Self_Cancelled_Appt_T3','Self_Cancelled_Screening_T3','Delay_Suspicious_T3'))
  
  return(cpath.model.fit)
}  


# Time 1

#Outcome = any patient-cancelled appointment
set.seed(1)
cpath_General_Any <- contemporaneousUnmediatedFit('cfi_mean_T1','Any_Self_Cancelled_Appt_T1')
summary(cpath_General_Any)

set.seed(1)
cpath_Cancer_Any <- contemporaneousUnmediatedFit('cfi_survivor_mean_T1','Any_Self_Cancelled_Appt_T1')
summary(cpath_Cancer_Any)

#Outcome = patient-cancelled cancer screening
set.seed(1)
cpath_General_Screen <- contemporaneousUnmediatedFit('cfi_mean_T1','Self_Cancelled_Screening_T1')
summary(cpath_General_Screen)

set.seed(1)
cpath_Cancer_Screen <- contemporaneousUnmediatedFit('cfi_survivor_mean_T1','Self_Cancelled_Screening_T1')
summary(cpath_Cancer_Screen)

#Outcome = delaying appointment for suspicious symptom
set.seed(1)
cpath_General_Delay <- contemporaneousUnmediatedFit('cfi_mean_T1','Delay_Suspicious_T1')
summary(cpath_General_Delay)

set.seed(1)
cpath_Cancer_Delay <- contemporaneousUnmediatedFit('cfi_survivor_mean_T1','Delay_Suspicious_T1')
summary(cpath_Cancer_Delay)


#________________________________________________________________________________________________________

# Time 2

#Outcome = any patient-cancelled appointment
set.seed(1)
cpath_General_Any2 <- contemporaneousUnmediatedFit('cfi_mean_T2','Any_Self_Cancelled_Appt_T2')
summary(cpath_General_Any2)

set.seed(1)
cpath_Cancer_Any2 <- contemporaneousUnmediatedFit('cfi_survivor_mean_T2','Any_Self_Cancelled_Appt_T2')
summary(cpath_Cancer_Any2)



#Outcome = patient-cancelled cancer screening
set.seed(1)
cpath_General_Screen2 <- contemporaneousUnmediatedFit('cfi_mean_T2','Self_Cancelled_Screening_T2')
summary(cpath_General_Screen2)

set.seed(1)
cpath_Cancer_Screen2 <- contemporaneousUnmediatedFit('cfi_survivor_mean_T2','Self_Cancelled_Screening_T2')
summary(cpath_Cancer_Screen2)



#Outcome = delaying appointment for suspicious symptom
set.seed(1)
cpath_General_Delay2 <- contemporaneousUnmediatedFit('cfi_mean_T2','Delay_Suspicious_T2')
summary(cpath_General_Delay2)

set.seed(1)
cpath_Cancer_Delay2 <- contemporaneousUnmediatedFit('cfi_survivor_mean_T2','Delay_Suspicious_T2')
summary(cpath_Cancer_Delay2)
  
```

#Time 3 Correlations
```{r}
install.packages("Hmisc")
library("Hmisc")


#Boulder data
newdata <- data[c("cfi_mean_T3", "cfi_survivor_mean_T3","gad7_tot_T3","phq8_tot_T3","copefull_ACS_mean_T3","copefull_AvCS_mean_T3","Any_Self_Cancelled_Appt_T3","Self_Cancelled_Screening_T3","Delay_Suspicious_T3")]

corr <- rcorr(as.matrix(newdata))
corr


#UCLA data

setwd("/Users/laurenfinkelstein/Desktop/Arch Lab/COVID Appt Paper/UCLA")
data_UCLA <-read.csv("UCLA Select Data.csv", header=T, na.strings=".")
View(data_UCLA)

#Predictors:

#Notes: UCLA seems to have only collected CFI 5 and 6 for general COVID fears and CFI 1, 2, and 3 for survivor-specific COVID fears. I believe our data averages across 10 cfi items for general and 5 for survivor-specific fears

data_UCLA$cfi_mean_T3 <- (data_UCLA$cfi_5_T3 + data_UCLA$cfi_6_T3)/2
data_UCLA$cfi_survivor_mean_T3 <- (data_UCLA$cfi_2_1 + data_UCLA$cfi_2_2 + data_UCLA$cfi_2_3)/3


#Mediators: gad7_tot_T3, phq8_tot_T3, Avoidance_Coping, Approach_Coping


#Outcomes
data_UCLA <- 
   data_UCLA %>%
   
   mutate(adh_cancer_you_T3 = factor(adh_cancer_you_T3,
                                     levels = c(0,1,2,3),
                                     labels = c('No','Yes', 'Not sure', 'I did not have anything scheduled')),
          adh_cancer_test_you_T3 = factor(adh_cancer_test_you_T3,
                                      levels = c(0,1,2,3),
                                      labels = c('No','Yes','Not Sure', 'I did not have anything scheduled')),
         adh_cancer_sx_T3 = factor(adh_cancer_sx_T3,
                                          levels = c(1,2,3,4,5),
                                          labels = c('Extremely unlikely','Unlikely','Neutral','Likely','Extremely Likely')))
 
table(data_UCLA$adh_cancer_you_T3)        
table(data_UCLA$adh_cancer_test_you_T3)  
table(data_UCLA$adh_cancer_sx_T3)  


data_UCLA <-
   data_UCLA %>%
   mutate(Any_Self_Cancelled_Appt_T3 = (adh_cancer_you_T3 == "Yes" | adh_cancer_test_you_T3 == "Yes"),
          Self_Cancelled_Screening_T3 = (adh_cancer_test_you_T3 == "Yes"),
          #Per 8/6/21 group discussion, extremely unlikely + unlikely = no delay (false) and neutral + Likely + extremely likely = yes delay (true)
          Delay_Suspicious_T3 = (adh_cancer_sx_T3 == "Neutral" | adh_cancer_sx_T3 == "Likely" | adh_cancer_sx_T3 == "Extremely Likely"))
 
table(data_UCLA$Any_Self_Cancelled_Appt_T3)
table(data_UCLA$Self_Cancelled_Screening_T3)
table(data_UCLA$Delay_Suspicious_T3)


newdata_UCLA <- data_UCLA[c("cfi_mean_T3", "cfi_survivor_mean_T3","gad7_tot_T3","phq8_tot_T3","Avoidance_Coping","Approach_Coping","Any_Self_Cancelled_Appt_T3","Self_Cancelled_Screening_T3","Delay_Suspicious_T3")]

View(newdata_UCLA)

corr_UCLA <- rcorr(as.matrix(newdata_UCLA))
corr_UCLA

```



