---
title: "Regression Models"
output: html_document
---

```{r}
install.packages("gitcreds")
library(gitcreds)

gitcreds_set()
gitcreds_get()

install.packages("credentials")
library(credentials)

set_github_pat()
```

```{r}

library(lavaan) 
library(psych)
library(car)
setwd("/Users/laurenfinkelstein/Desktop/Arch Lab/COVID Appt Paper/Data")
data <-read.csv("CURRENT Full Covid Data.csv", header=T)
View(data)

```

#Time 1 single predictor and multivariate models
```{r}
#Anxiety
anxiety1 <- glm(Any_Self_Cancelled_Appt_T1 ~ gad7_tot_T1, data=data, family=binomial)
summary(anxiety1)
coef(anxiety1)
exp(coef(anxiety1))

#Depression
dep1 <- glm(Any_Self_Cancelled_Appt_T1 ~ phq8_tot_T1, data=data, family=binomial)
summary(dep1)
coef(dep1)
exp(coef(dep1))

#General COVID fears
fear1 <- glm(Any_Self_Cancelled_Appt_T1 ~ cfi_mean_T1, data=data, family=binomial)
summary(fear1)
coef(fear1)
exp(coef(fear1))

#Cancer-specific COVID fears
canc_fear1 <- glm(Any_Self_Cancelled_Appt_T1 ~ cfi_survivor_mean_T1, data=data, family=binomial)
summary(canc_fear1)
coef(canc_fear1)
exp(coef(canc_fear1))


#Multivariate
multi1 <- glm(Any_Self_Cancelled_Appt_T1 ~ gad7_tot_T1 + phq8_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1, data=data, family=binomial)
summary(multi1)
coef(multi1)
exp(coef(multi1))
vif(multi1)

#Separate depression/anxiety multivariate models

#Anxiety
multianx1 <- glm(Any_Self_Cancelled_Appt_T1 ~ gad7_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1, data=data, family=binomial)
summary(multianx1)
coef(multianx1)
exp(coef(multianx1))
vif(multianx1)

#With econ impact
multianx1econ <- glm(Any_Self_Cancelled_Appt_T1 ~ gad7_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1 + covid19_impact_econ_T1, data=data, family=binomial)
summary(multianx1econ)
coef(multianx1econ)
exp(coef(multianx1econ))
vif(multianx1econ)

#Depression
multidep1 <- glm(Any_Self_Cancelled_Appt_T1 ~ phq8_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1, data=data, family=binomial)
summary(multidep1)
coef(multidep1)
exp(coef(multidep1))
vif(multidep1)

#With econ impact
multidep1econ <- glm(Any_Self_Cancelled_Appt_T1 ~ phq8_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1 + covid19_impact_econ_T1, data=data, family=binomial)
summary(multidep1econ)
coef(multidep1econ)
exp(coef(multidep1econ))
vif(multidep1econ)


```

#Time 2 single predictor and multivariate models
```{r}
#Anxiety
anxiety2 <- glm(Any_Self_Cancelled_Appt_T2 ~ gad7_tot_T2, data=data, family=binomial)
summary(anxiety2)
coef(anxiety2)
exp(coef(anxiety2))

#Depression
dep2 <- glm(Any_Self_Cancelled_Appt_T2 ~ phq8_tot_T2, data=data, family=binomial)
summary(dep2)
coef(dep2)
exp(coef(dep2))

#General COVID fears
fear2 <- glm(Any_Self_Cancelled_Appt_T2 ~ cfi_mean_T2, data=data, family=binomial)
summary(fear2)
coef(fear2)
exp(coef(fear2))

#Cancer-specific COVID fears
canc_fear2 <- glm(Any_Self_Cancelled_Appt_T2 ~ cfi_survivor_mean_T2, data=data, family=binomial)
summary(canc_fear2)
coef(canc_fear2)
exp(coef(canc_fear2))




#Multivariate
multi2 <- glm(Any_Self_Cancelled_Appt_T2 ~ gad7_tot_T2 + phq8_tot_T2 + cfi_mean_T2 + cfi_survivor_mean_T2, data=data, family=binomial)
summary(multi2)
coef(multi2)
exp(coef(multi2))
vif(multi2)


#Separate depression/anxiety multivariate models


library(psych)
library(lme4)
library(lmerTest)
library(sjPlot)
library(car)
library(lmSupport)
library(pwr)
source('http://psych.colorado.edu/~jclab/R/mcSummaryLm.R')

#Anxiety
multianx2 <- glm(Any_Self_Cancelled_Appt_T2 ~ gad7_tot_T2 + cfi_mean_T2 + cfi_survivor_mean_T2, data=data, family=binomial)
summary(multianx2)
coef(multianx2)
exp(coef(multianx2))
vif(multianx2)

#With econ impact
multianx2econ <- glm(Any_Self_Cancelled_Appt_T2 ~ gad7_tot_T2 + cfi_mean_T2 + cfi_survivor_mean_T2 + covid19_impact_econ_T2, data=data, family=binomial)
summary(multianx2econ)
coef(multianx2econ)
exp(coef(multianx2econ))
vif(multianx2econ)


#Depression
multidep2 <- glm(Any_Self_Cancelled_Appt_T2 ~ phq8_tot_T2 + cfi_mean_T2 + cfi_survivor_mean_T2, data=data, family=binomial)
summary(multidep2)
coef(multidep2)
exp(coef(multidep2))
vif(multidep2)

#With econ impact
multidep2econ <- glm(Any_Self_Cancelled_Appt_T2 ~ phq8_tot_T2 + cfi_mean_T2 + cfi_survivor_mean_T2 + covid19_impact_econ_T2, data=data, family=binomial)
summary(multidep2econ)
coef(multidep2econ)
exp(coef(multidep2econ))
vif(multidep2econ)

table(data$covid19_impact_econ_T1)
```

#Time 3 single predictor and multivariate models
```{r}
#Anxiety
anxiety3 <- glm(Any_Self_Cancelled_Appt_T3 ~ gad7_tot_T3, data=data, family=binomial)
summary(anxiety3)
coef(anxiety3)
exp(coef(anxiety3))

#Depression
dep3 <- glm(Any_Self_Cancelled_Appt_T3 ~ phq8_tot_T3, data=data, family=binomial)
summary(dep3)
coef(dep3)
exp(coef(dep3))

#General COVID fears
fear3 <- glm(Any_Self_Cancelled_Appt_T3 ~ cfi_mean_T3, data=data, family=binomial)
summary(fear3)
coef(fear3)
exp(coef(fear3))

#Cancer-specific COVID fears
canc_fear3 <- glm(Any_Self_Cancelled_Appt_T3 ~ cfi_survivor_mean_T3, data=data, family=binomial)
summary(canc_fear3)
coef(canc_fear3)
exp(coef(canc_fear3))



#Multivariate
multi3 <- glm(Any_Self_Cancelled_Appt_T3 ~ gad7_tot_T3 + phq8_tot_T3 + cfi_mean_T3 + cfi_survivor_mean_T3, data=data, family=binomial)
summary(multi3)
coef(multi3)
exp(coef(multi3))
vif(multi3)


#Separate depression/anxiety multivariate models
multianx3 <- glm(Any_Self_Cancelled_Appt_T3 ~ gad7_tot_T3 + cfi_mean_T3 + cfi_survivor_mean_T3, data=data, family=binomial)
summary(multianx3)
coef(multianx3)
exp(coef(multianx3))
vif(multianx3)


multidep3 <- glm(Any_Self_Cancelled_Appt_T3 ~ phq8_tot_T3 + cfi_mean_T3 + cfi_survivor_mean_T3, data=data, family=binomial)
summary(multidep3)
coef(multidep3)
exp(coef(multidep3))
vif(multidep3)
```

```{r}
count(data$Any_Self_Cancelled_Appt_T1 == 'TRUE' | data$Any_Self_Cancelled_Appt_T2 == 'FALSE' | data$Any_Self_Cancelled_Appt_T3 == 'FALSE')
```

#Time-lagged models
```{r}

#T2 any patient-cancelled appointment ~ T1 predictors

#Anxiety
multianxT1T2 <- glm(Any_Self_Cancelled_Appt_T2 ~ gad7_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1, data=data, family=binomial)
summary(multianxT1T2)
coef(multianxT1T2)
exp(coef(multianxT1T2))
vif(multianxT1T2)

#Depression
multidepT1T2 <- glm(Any_Self_Cancelled_Appt_T2 ~ phq8_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1, data=data, family=binomial)
summary(multidepT1T2)
coef(multidepT1T2)
exp(coef(multidepT1T2))
vif(multidepT1T2)



#T3 any patient-cancelled appointment ~ T2 predictors

#Anxiety
multianxT2T3 <- glm(Any_Self_Cancelled_Appt_T3 ~ gad7_tot_T2 + cfi_mean_T2 + cfi_survivor_mean_T2, data=data, family=binomial)
summary(multianxT2T3)
coef(multianxT2T3)
exp(coef(multianxT2T3))
vif(multianxT2T3)

#Depression
multidepT2T3 <- glm(Any_Self_Cancelled_Appt_T3 ~ phq8_tot_T2 + cfi_mean_T2 + cfi_survivor_mean_T2, data=data, family=binomial)
summary(multidepT2T3)
coef(multidepT2T3)
exp(coef(multidepT2T3))
vif(multidepT2T3)



#T3 any patient-cancelled appointment ~ T1 predictors

#Anxiety
multianxT1T3 <- glm(Any_Self_Cancelled_Appt_T3 ~ gad7_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1, data=data, family=binomial)
summary(multianxT1T3)
coef(multianxT1T3)
exp(coef(multianxT1T3))
vif(multianxT1T3)

#Depression
multidepT1T3 <- glm(Any_Self_Cancelled_Appt_T3 ~ phq8_tot_T1 + cfi_mean_T1 + cfi_survivor_mean_T1, data=data, family=binomial)
summary(multidepT1T3)
coef(multidepT1T3)
exp(coef(multidepT1T3))
vif(multidepT1T3)

```
#General COVID fears and anxiety/depression (time-lagged)
```{r}
#Anxiety predicting general COVID fears
Covid_anx1 <- glm(cfi_mean_T2 ~ gad7_tot_T1, data=data)
summary(Covid_anx1)

Covid_anx2 <- glm(cfi_mean_T3 ~ gad7_tot_T2, data=data)
summary(Covid_anx2)

#Depression predicting general COVID fears
Covid_dep1 <- glm(cfi_mean_T2 ~ phq8_tot_T1, data=data)
summary(Covid_dep1)

Covid_dep2 <- glm(cfi_mean_T3 ~ phq8_tot_T2, data=data)
summary(Covid_dep2)

#General COVID fears predicting anxiety
Anx_covid1 <- glm(gad7_tot_T2 ~ cfi_mean_T1, data=data)
summary(Anx_covid1)

Anx_covid2 <- glm(gad7_tot_T3 ~ cfi_mean_T2, data=data)
summary(Anx_covid2)

#General COVID fears predicting depression
Dep_covid1 <- glm(phq8_tot_T2 ~ cfi_mean_T1, data=data)
summary(Dep_covid1)

Dep_covid2 <- glm(phq8_tot_T3 ~ cfi_mean_T2, data=data)
summary(Dep_covid2)




```

#General COVID fears and anxiety/depression (time-lagged, including outcome at T-1 as predictor)
```{r}
#Anxiety predicting general COVID fears
Covid_anx1a <- glm(cfi_mean_T2 ~ gad7_tot_T1 + cfi_mean_T1, data=data)
summary(Covid_anx1a)

Covid_anx2a <- glm(cfi_mean_T3 ~ gad7_tot_T2 + cfi_mean_T2, data=data)
summary(Covid_anx2a)

#Depression predicting general COVID fears
Covid_dep1a <- glm(cfi_mean_T2 ~ phq8_tot_T1 + cfi_mean_T1, data=data)
summary(Covid_dep1a)

Covid_dep2a <- glm(cfi_mean_T3 ~ phq8_tot_T2 + cfi_mean_T2, data=data)
summary(Covid_dep2a)

#General COVID fears predicting anxiety
Anx_covid1a <- glm(gad7_tot_T2 ~ cfi_mean_T1 + gad7_tot_T1, data=data)
summary(Anx_covid1a)

Anx_covid2a <- glm(gad7_tot_T3 ~ cfi_mean_T2 + gad7_tot_T2, data=data)
summary(Anx_covid2a)

#General COVID fears predicting depression
Dep_covid1a <- glm(phq8_tot_T2 ~ cfi_mean_T1 + phq8_tot_T1, data=data)
summary(Dep_covid1a)

Dep_covid2a <- glm(phq8_tot_T3 ~ cfi_mean_T2 + phq8_tot_T2, data=data)
summary(Dep_covid2a)
```
```{r}
#Examining correlations to get insight as to why models did not hold up when including outcome at T-1 as predictor


newdata <- data[c("gad7_tot_T1", "gad7_tot_T2", "gad7_tot_T3", "phq8_tot_T1", "phq8_tot_T2", "phq8_tot_T3", "cfi_mean_T1", "cfi_mean_T2", "cfi_mean_T3")]

View(newdata)

corr <- rcorr(as.matrix(newdata))
corr
```

